### ISSUE TITLE
Assalamualaikum Kangphp 🙏

### ISSUE THREAD

**Issue by Buddiwijaya** [kangphp/bigtoken#1]
Assalamualaikum kangphp 🙏
Saya mau tanya cara masukan code SBG bagaimana ya.. ini untuk masukan lewat termux tolong pencerahannya.. 🙏

**Comment by kangphp** [comment]
Halo mas budi, untuk source code ini udh exp, ga bisa di pakai lagi. Terima kasih 🙏
